### ISSUE TITLE
Merge pull request

### ISSUE THREAD

**Issue by conrad-dk** [etyp/meteor-accounts-ldap#30]
The outstanding pull request by @billiam13s solves two critical bugs. Can we get those merged in or should I create a fork and do it there?

@etyp I guess you aren't too involved with this any more?

**Comment by etyp** [comment]
@conrad-dk I'm sorry, I've been really swamped and meant to update everyone. I plan on trying to catch up on issues and PRs at some point, but can't make promises on when.

I'm aiming for this weekend when I have extra time. In the meantime, I've added you as a collaborator on the project. Feel free to move forward with PRs.

**Comment by conrad-dk** [comment]
Finally got around to it - it worked perfectly for me, so I've gone ahead and merged the PR.
